apiVersion: v1
kind: Service
metadata:
  name: app-register-service
  labels:
    app: app-register 
spec:
  selector:
    app: app-register

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer